name: ubuntu-build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ci-${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cmake:
    runs-on: ubuntu-22.04
    steps:
      - name: Show env
        run: env

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Build Dependencies
        shell: bash
        run: |
          sudo apt update && sudo apt install --no-install-recommends -y \
          cmake \
          make

      - name: Show Python version and platform info
        run: |
          python --version
          python -m platform

      - name: Show CMake version
        run: cmake --version

      - name: CMake Configure
        shell: bash
        run: |
          cmake -S . -B build -DCMAKE_VERBOSE_MAKEFILE=ON

      - name: CMake Build
        shell: bash
        run: |
          cmake --build build -j$(nproc)

  bazel:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: bazel-contrib/setup-bazel@0.8.4
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - run: BAZEL_CXXOPTS="-std=c++17" bazel test //...
      - run: BAZEL_CXXOPTS="-std=c++20" bazel test //...
